Shoot death fx
NestorTejero/ES2016B pull request #230
Opened 2016-11-19 11:53 UTC by vcampoma7

- Added random death sound
- Changed Sound directory path

2016-11-19 12:32 UTC, ifernapa10 approved these changes
Todo correcto sin conflictos.

2016-11-21 18:58 UTC, kkaren requested changes

2016-11-21 18:58 UTC, kkaren commented on Assets/Scripts/Model/Weapon.cs
> +        if (!this.source_death.isPlaying)
Aquí no es el momento exacto en que muere el target, simplemente se elimina de la lista de targets (no se muy bien que sonido es pero quizá se debería hacer sonar en Unit y no en Weapon).

2016-11-21 18:58 UTC, kkaren commented on Assets/Scripts/Model/Weapon.cs
> +    public AudioClip shootSound, deathSound1, deathSound2, deathSound3;
Para que hacen falta deathSound1, deathSound2 y deathSound3 si se cargan internamente en Start() ?

2016-11-21 18:58 UTC, kkaren commented on Assets/Scripts/Model/Weapon.cs
> +    public AudioSource source_shoot, source_death;
Esto se debería asignar internamente en código (con tags quizá) y ser private.

2016-11-21 18:58 UTC, kkaren commented on Assets/Scripts/Model/Weapon.cs
> +    public AudioClip[] death;
Debería ser private.

2016-11-23 18:21 UTC, vcampoma7 commented on Assets/Scripts/Model/Weapon.cs
> +    public AudioClip shootSound, deathSound1, deathSound2, deathSound3;
tienes razón, eso sobra

2016-11-23 18:22 UTC, vcampoma7 commented on Assets/Scripts/Model/Weapon.cs
> +        if (!this.source_death.isPlaying)
Ok, mea culpa, pensé que el método RemoveTarget eliminava el objetivo. Lo traspaso en el nuevo Sprint

2016-12-03 11:01 UTC, closed without merging

2016-12-12 20:31 UTC, NestorTejero commented
milestone? labels?