Unit animation and scripts
NestorTejero/ES2016B pull request #308
Opened 2016-12-01 22:45 UTC by sashadgt

Fixed prefabs, still need adjustements and fixes in colliders and small things
Created AnimationControllers for all Units
Created UnitAnimation.cs script for controlling said animations
Call Animations When unit is Created , Walks , Attacks and Dies
Fixed Unit Navmesh to corectly use data in Unit.cs 
refactored some Code in Unit.cs

2016-12-01 22:51 UTC, sashadgt commented
Issue Link https://github.com/NestorTejero/ES2016B/issues/291

2016-12-02 11:55 UTC, kkaren requested changes
He revisado el código y he ejecutado la rama. Si no se cambia lo que he comentado del trigger de los colliders, las torres nunca detectan enemigos y no disparan. Por lo demás, todo correcto.

2016-12-02 11:55 UTC, kkaren commented on Assets/Prefabs/Units/Freshman_student.prefab
> +  m_IsTrigger: 1
El Collider del modelo de todos los prefabs de las Units (el de dentro) no tiene que ser trigger, sólo el de fuera.

2016-12-02 11:55 UTC, kkaren commented on Assets/Scripts/Model/Weapon.cs
> +            animScript.Attack();
Qué animación es Attack exactamente, y porqué es la única que no se llama dentro del script de la Unit en particular?

2016-12-02 12:00 UTC, sashadgt commented on Assets/Prefabs/Units/Freshman_student.prefab
> +  m_IsTrigger: 1
Ok perrfect, lo quto i lo subo bien

2016-12-02 12:05 UTC, sashadgt commented on Assets/Prefabs/Units/Freshman_student.prefab
> +  m_IsTrigger: 1
**DONE**

2016-12-02 12:24 UTC, kkaren approved these changes
Perfecto!

2016-12-02 12:41 UTC, merged