Ability
NestorTejero/ES2016B pull request #329
Opened 2016-12-09 19:02 UTC by JoanBenito

- Ahora las oleadas hacen respawn en dos de los cuatro spawn points que hay en la escena, se eligen random.
- Al pulsar la tecla "J" se activa el poder.
- El poder termina cuando acaba la oleada.
- Ahora los objetos respawn points de la escena tienen componentes halo, de tamaño 10 y color rojo.
- TODO: elegir coste o cooldown de la habilidad y tiempo de duración.

2016-12-10 16:20 UTC, Solero93 requested changes
What have you changed on the scene? 

I'll try out what you've done when I arrive to BCN

2016-12-10 16:20 UTC, Solero93 commented on Assets/Scripts/Model/UnitShop.cs
> +	private bool flag = false;
Could this name be a bit more descriptive?

2016-12-10 16:42 UTC, JoanBenito commented
Lo he puesto en la descripción, toco únicamente los respawn point en la escena, les añado un componente halo. No es peligroso jaja

2016-12-10 16:45 UTC, Solero93 commented
yo voy a sudar ya, pero pa futuros proyectos el respawn point debería ser prefab jajaja

2016-12-10 16:49 UTC, JoanBenito commented
Bueno yo como me lo he encontrado, cómo fue una issue pasada, pensé que se quería así y por eso lo he dejado tal cuál. Se puede mirar para el mini sprint de hacerla prefab xD

2016-12-11 12:03 UTC, Solero93 commented
Estoy probando de spamear la tecla J y no veo que cambie nada.. qué debería ver?

2016-12-11 12:06 UTC, JoanBenito commented
en la escena, los puntos de respawn se iluminan de color rojo. Mira si se ha hecho bien el merge con la escena y tienen el componente halo... si no lo tienen es que  no se ha hecho bien.

2016-12-11 12:08 UTC, Solero93 commented
@JoanBenito lo siento, yo tengo que revisar la PR de @sashadgt tmb y hacer otra tarea mía xd no tengo tiempo de arreglar ahora el tuyo

Si eso cuando acabe esto y las entregas de VA me lo puedo mirar... pero míralo tú mejor a ver

2016-12-11 12:10 UTC, JoanBenito commented
Arreglar el qué? A mi me aparece bien.

2016-12-11 12:20 UTC, Solero93 commented
ostias... ya lo veo xD es que era taaan sutil que ni me enteré xD no puedes poner un punto verde o alguna cosa en el minimapa?

2016-12-11 12:22 UTC, JoanBenito commented
aún no había mini mapa cuando lo hice, intentaré hacerlo pero estoy liado con iad, sino lo hago para el mini sprint 5.
Igualmente he encontrado un bug ahora, ya te diré.

2016-12-11 12:24 UTC, Solero93 commented
Acabo de mergear con dev pa que no te salten conflictos luego y que vayas actualizado

2016-12-11 13:02 UTC, Solero93 reviewed
4 comentarios chorras, respóndeme y te acepto ya dp de arreglar los conflictos en la PR de @iubeda

2016-12-11 13:02 UTC, Solero93 commented on Assets/Scripts/Controller/GameController.cs
> +			spawnPoint2 =  Random.Range(0, 4);
jajajajajaja me encanta! sería mejor pero hacer spawnPoint2 = (spawnPoint1 + 1) % 4 o algo por el estilo. Pero bueno, esto es algo menor

2016-12-11 13:02 UTC, Solero93 commented on Assets/Scripts/Controller/GameController.cs
> +		((Behaviour)respawns [spawnPoint1].GetComponent ("Halo")).enabled = true;
Por mera curiosidad, por qué casteas a Behaviour?

2016-12-11 14:40 UTC, Solero93 approved these changes

2016-12-11 21:08 UTC, Solero93 requested changes
Más cosas... Con eso hay que ir con cuidado

2016-12-11 21:08 UTC, Solero93 commented on Assets/Scripts/Controller/GameController.cs
> +			spawnPoint2 =  Random.Range(0, 4);
O incluso mejor... spawnPoint2 = (spawnPoint1 + Random.Range(1,4)) % 4

2016-12-11 21:08 UTC, Solero93 commented on Assets/Scripts/Controller/GameController.cs
> +			spawnPoint2 =  Random.Range(0, 4);
de hecho Joan... peor todavía porque Random.Range(0,4) puede ser 0,1,2,3,4 y solo hay 4 spawnpoints!

2016-12-12 19:55 UTC, Solero93 approved these changes

2016-12-12 19:56 UTC, merged